CREATE TABLE users(
    id UUID PRIMARY KEY,
    username VARCHAR(255),
    password VARCHAR(255),
    document VARCHAR(11) NOT NULL,
    email VARCHAR(255) NOT NULL,
    role VARCHAR(255),
    created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT uk_email UNIQUE (email),
    CONSTRAINT uk_document UNIQUE (document)
);